name: Release to PyPI

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          echo "----- dist contents -----"
          ls -lah dist
          echo "----- twine check -----"
          python -m twine check dist/*

      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
